# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ldpc', [dirname(__file__)])
        except ImportError:
            import _ldpc
            return _ldpc
        if fp is not None:
            try:
                _mod = imp.load_module('_ldpc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ldpc = swig_import_helper()
    del swig_import_helper
else:
    import _ldpc
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class ControlFSM(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ControlFSM, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ControlFSM, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ldpc.new_ControlFSM()
        try: self.this.append(this)
        except: self.this = this
    def setState(self, *args): return _ldpc.ControlFSM_setState(self, *args)
    def getState(self): return _ldpc.ControlFSM_getState(self)
    __swig_destroy__ = _ldpc.delete_ControlFSM
    __del__ = lambda self : None;
ControlFSM_swigregister = _ldpc.ControlFSM_swigregister
ControlFSM_swigregister(ControlFSM)

class FP_Encoder(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FP_Encoder, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FP_Encoder, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ldpc.new_FP_Encoder()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ldpc.delete_FP_Encoder
    __del__ = lambda self : None;
    def encode(self, *args): return _ldpc.FP_Encoder_encode(self, *args)
    def loadfile(self, *args): return _ldpc.FP_Encoder_loadfile(self, *args)
FP_Encoder_swigregister = _ldpc.FP_Encoder_swigregister
FP_Encoder_swigregister(FP_Encoder)


def create_enc_obj():
  return _ldpc.create_enc_obj()
create_enc_obj = _ldpc.create_enc_obj

def destroy_enc_obj(*args):
  return _ldpc.destroy_enc_obj(*args)
destroy_enc_obj = _ldpc.destroy_enc_obj

def create_dec_obj():
  return _ldpc.create_dec_obj()
create_dec_obj = _ldpc.create_dec_obj

def destroy_dec_obj(*args):
  return _ldpc.destroy_dec_obj(*args)
destroy_dec_obj = _ldpc.destroy_dec_obj

def encode_ldpc(*args):
  return _ldpc.encode_ldpc(*args)
encode_ldpc = _ldpc.encode_ldpc

def decode_ldpc(*args):
  return _ldpc.decode_ldpc(*args)
decode_ldpc = _ldpc.decode_ldpc
# This file is compatible with both classic and new-style classes.


